### ISSUE TITLE
Composed

### ISSUE THREAD

**Issue by shaps80** [lxcid/ComposeKit#1]
If you (or anyone else seeing this) are interested in a more Swifty approach to the same problem checkout my github Organization which provides multiple Swift packages that can be used together.

The two primary packages you’d be interested in would be:

1. [Composed](github.com/composed-swift/composed)
2. [ComposedUI](github.com/composed-swift/composedui)

There is also a demo project at:
[Composed Demo](github.com/composed-swift/composed-demo)

The library supports UICollectionView, UITableView and UIStackView as well as various types of sources, CoreData, Photo Library, pure Arrays, etc...

It’s a complete library that’s been in development and used in production apps for over 2 years now. Any issues, please submit issues on the appropriate repos.

**Comment by lxcid** [comment]
Sure man. You mind sending me a PR to update my README.md so I can send ppl to your repo as I no longer active on this project. It would be great people can use a more maintained version. :)

**Comment by shaps80** [comment]
For sure, I’ll do that shortly. Thanks.
